// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using CrudPersonasWebApi.Models;

namespace CrudPersonasWebApi.Migrations
{
    [DbContext(typeof(CrudPersonasWebApiContext))]
    [Migration("20221005182044_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("pruebaWebApi.Models.ContactMean", b =>
                {
                    b.Property<int>("ContactMeansId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ContactMeansId")
                        .HasName("PK__ContactM__9F789A2F1523E0AF");

                    b.ToTable("ContactMeans");
                });

            modelBuilder.Entity("pruebaWebApi.Models.ContactMeansPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ContactMeansId")
                        .HasColumnType("integer");

                    b.Property<int?>("PersonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContactMeansId");

                    b.HasIndex("PersonId");

                    b.ToTable("ContactMeansPerson");
                });

            modelBuilder.Entity("pruebaWebApi.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Birth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("pruebaWebApi.Models.ContactMeansPerson", b =>
                {
                    b.HasOne("pruebaWebApi.Models.ContactMean", "ContactMeans")
                        .WithMany("ContactMeansPeople")
                        .HasForeignKey("ContactMeansId")
                        .HasConstraintName("FK__ContactMe__Conta__3F466844");

                    b.HasOne("pruebaWebApi.Models.Person", "Person")
                        .WithMany("ContactMeansPeople")
                        .HasForeignKey("PersonId")
                        .HasConstraintName("FK__ContactMe__Perso__403A8C7D");

                    b.Navigation("ContactMeans");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("pruebaWebApi.Models.ContactMean", b =>
                {
                    b.Navigation("ContactMeansPeople");
                });

            modelBuilder.Entity("pruebaWebApi.Models.Person", b =>
                {
                    b.Navigation("ContactMeansPeople");
                });
#pragma warning restore 612, 618
        }
    }
}
